# Create weather grid using conteStreamflow package

### Load package
```{r pkgs}

# library(devtools)
# install_github( repo="conteStreamflow", username="anarosner" )
setwd("C:/ALR/Models/conteStreamflow/r")
for (i in list.files()) 
     source(i)

library(conteStreamflow)
```

### Create weather grid coordinates from file contents
```{r create weather grid, cache=TRUE}

#Will only need to do this very occassionally, when adding a new geographic region

setwd("C:/ALR/Data/ClimateData/Livneh/B_1950_2013/grid")
weather.grid.coords <- weather.grid.livneh.coords( ftp.url="ftp://gdo-dcp.ucllnl.org/pub/dcp/archive/OBS/livneh2014.1_16deg/ascii/daily/" )
save( weather.grid.coords, file="weather_grid_coords.rdata" )
```


### Create weather grid points.  Select points in geogrpahic region to turn to grid
```{r}
# source("C:/ALR/Models/conteStreamflow/r/create_templates_livneh_weather.R")

#create spatial points data frame
weather.grid.points <- weather.grid.livneh.points( weather.grid.coords )

#see size
nrow(weather.grid.points)

#load states spatial data
cache.set( "c:/alr/models/cache")
cache.load.data( object="states.poly", "states.rdata", dir="general_spatial") 
plot(states.poly)

#select states
ne.states <- states.poly[states.poly$STUSPS %in% c("MA","CT","NY","NH","VT","ME","RI"),]


#plot to see overlap.  
plot(ne.states)
plot(weather.grid.points,add=T, col="blue")

#compare bounding boxes
bbox(ne.states)
bbox(weather.grid.points)

#create complilation bounding box, to get the extra data east of the Maine boundary
box <- bbox(ne.states)
box[1,2] <- bbox(weather.grid.points)[1,2]
box


## Load raster package (event though we're not working w/ rasters) 
#    to use crop function to clip SpatialPolygonsDataFrame
# install.packages("raster")
library(raster) 

## Crop to the desired extent, then plot
weather.grid.points.crop <- crop( weather.grid.points, box )

#plot results
plot(weather.grid.points, col="red")
plot(states.poly, add=T)
plot(weather.grid.points.crop, col="blue", add=T)




```



### Create weather grid polygons from coordinates
```{r}

nrow(weather.grid.points.crop)
weather.grid.poly <- weather.grid.livneh.create( grid.points=weather.grid.points.crop )

save( weather.grid.poly, file="weather_grid_poly.rdata" )



```

### Plot
```{r}

plot(weather.grid.poly)
plot(weather.grid.points,add=T, col="blue")



```

### Create template of dates
```{r}
#these are hard-coded for now, but they should be read from a file within the livneh 1950-2013 set folder
start_date <- "1950-01-01"
end_date <- "2013-12-31"

# this isn't really necessary, but it's reassuring that the number of records match the number of dates! 
# because unfortunately, the date isn't part of the weather record
example_file <- read.table("C:/ALR/Data/ClimateData/Livneh/B_1950_2013/Meteorology_Livneh_NAmerExt_15Oct2014_16.59375_-90.65625.bz2" )
dim(example_file)

# calculate series of dates between the range specified for this set (livneh 1950-2013)
example_file$date <- seq.Date( from=as.Date(start_date), to=as.Date(end_date), by="day" )

# to save time later, we'll also calculate the dates representing the month and the water year for each record
example_file$month_date <- to_month_date( example_file$date )
example_file$wateryear_date <- to_wateryear_date( example_file$date )

head(example_file)
tail(example_file)
str(example_file)


template_w_date <- example_file[,c("date","month_date","wateryear_date")]
template_w_cols <- c("precip_mm", "tmax","tmin","wind")

head(template_date)

```


