
```{r}
#      boo <- x_calc %>% 
#           group_by_( paste0(j,"_date") ) %>% 
#           summarize( max_precip_e_date=max_which_date( precip_e, date ), 
#                      max_precip_e_ties=max_count_date( precip_e, date ),
#                      max_precip_raw_date=max_which_date( precip_raw, date ), 
#                      max_precip_raw_ties=max_count_date( precip_raw, date ),
#                      max_precip_3_date=max_which_date( precip_sum_3, date ), 
#                      max_precip_3_ties=max_count_date( precip_sum_3, date ),
#                      maxe=max(precip_e),
#                      maxr=max(precip_raw),
#                      max3=max(precip_sum_3),
#                      diff3=max_precip_e_date-max_precip_3_date ) 
#      View(boo)


```


```{r}

     
     
     
     
#                index <- x_calc %>% 
#                     group_by_( paste0(j,"_date") ) %>% 
#                     summarize( index=which.max( precip_e ) )
#                boo <- x_calc %>% 
#                     group_by_( paste0(j,"_date") )
#                boo[index,"date"]     
#                
#                
#                
#                
#                select( max_date )
#                index <- as.data.frame(index)[,1]
#                head(index)
#                x_summary$max_precip_e_date <-x_calc[index,"day_date"]
#                head(x_summary,10)
               
for ( k in cols_max_date ) {
     boo <- 
          x_calc %>% 
               group_by_( paste0(j,"_date") ) %>% 
               summarize_( max_date="max_which_date( precip_e, date )" ) 
          x_calc %>% 
               group_by_( paste0(j,"_date") ) %>% 
               summarize( max_date=max_which_date( precip_e, date ) ) 
     
     names(x_calc)
     
     mtcars %>% 
          group_by(cyl) %>% 
          summarise_(boo="mean(mpg)+mean(hp)")
               
                    x_calc %>% 
                         group_by_( paste0(j,"_date") ) %>% 
                         summarize( max_count=max_count_date( precip_e, day_date ) )  
                    x_calc %>% 
                         group_by_( paste0(j,"_date") ) %>% 
                         summarize( max_count=test_count_date( precip_e, day_date ) )  
                    
                    summarize( boo=max( precip_e ) )  
               
                    summarize( boo=max(precip_e ) ) 
                    # summarize_( "max_which_date", k, paste0(j,"_date") ) 
               x_max_which
               x_summary <- merge( x_summary, x_max_which, by=paste0(j,"_date") )
               x_max_which <- x_calc %>% 
                    group_by_( paste0(j,"_date") ) %>% 
                    summarize_( "max_count_date", k, paste0(j,"_date") ) 
               x_summary <- merge( x_summary, x_max_which, by=paste0(j,"_date") )
          }



# x_calc[x_calc$month_date == "1950-07-01","precip_e"]
max_which_date( x_calc[x_calc$month_date == "1950-07-01","precip_e"],
                x_calc[x_calc$month_date == "1950-07-01","day_date"])
# boo <- max_which( x_calc[x_calc$month_date == "1950-07-01","precip_e"])
# boo
# class(boo)
# x_calc[x_calc$month_date == "1950-07-01","day_date"][6]
#  
# max_which <- function( x ) {
#      #if all records are NA, return NA and escape function
#      if ( sum( !is.na(x) )==0 )
#           return( NA )
#      index <- which( x == max(x) )  #find index
#      return( index[1] )
# }


test_count_date <- function( col_min, col_date ) {
     #if all records are NA, return NA and escape function
     if ( sum( !is.na(col_min) )==0 )
          return( NA )
     row <- which( col_min == min(col_min) )  #find row w/ max value
     return( length(row) ) #return date for that row
          
}

# boo <- max_which_date( x_calc[x_calc$month_date == "1950-07-01",] )
# x_calc[x_calc$month_date == "1950-07-01","precip_e"]
# max_which_date( x_calc[x_calc$month_date == "1950-07-01",] )
# 
# max_which_date <- function( x_which, col_max="precip_e", col_date="day_date" ) {
#      #if all records are NA, return NA and escape function
#      if ( sum( !is.na(x_which[,col_max]) )==0 )
#           return( NA )
# 
#      row <- which( x_which[,col_max] == max(x_which[,col_max]) )  #find row w/ max value
#      return( x_which[row,col_date] ) #return date for that row
#           
# }

max_count_date <- function( x_which, col_max="precip_e", col_date="month_date" ) {
     if ( sum( !is.na(x_which[,col_max]) )==0 )
          return( NA )

     row <- which( x_which[,col_max] == max(x_which[,col_max]) ) #find rows w/ max value
     return( length(row) ) #return number of rows
}


```





```{r}
#      x[,"precip_ante_7"] <- rollsum( x$precip_e, k=7, align="right", fill=NA )
#      x[,"precip_ante_30"] <- rollsum( x$precip_e, k=30, align="right", fill=NA )
#      x[,"precip_ante_60"] <- rollsum( x$precip_e, k=60, align="right", fill=NA )
#      x <- slide( data=x, Var="precip_ante_7", NewVar="precip_ante_7", slideBy=-1, reminder=F )
#      x <- slide( data=x, Var="precip_ante_30", NewVar="precip_ante_30", slideBy=-1, reminder=F )
#      x <- slide( data=x, Var="precip_ante_60", NewVar="precip_ante_60", slideBy=-1, reminder=F )
#      x[,"pet_ante_30"] <- rollmean( x$pet, k=30, align="right", fill=NA )
#      x[,"pet_ante_60"] <- rollmean( x$pet, k=60, align="right", fill=NA )
#      x[,"pet_ante_90"] <- rollmean( x$pet, k=90, align="right", fill=NA )
#      x <- slide( data=x, Var="pet_ante_30", NewVar="pet_ante_30", slideBy=-1, reminder=F )
#      x <- slide( data=x, Var="pet_ante_60", NewVar="pet_ante_60", slideBy=-1, reminder=F )
#      x <- slide( data=x, Var="pet_ante_90", NewVar="pet_ante_90", slideBy=-1, reminder=F )
#      x[,"gdd_ante_30"] <- rollmean( x$gdd, k=30, align="right", fill=NA )
#      x[,"gdd_ante_60"] <- rollmean( x$gdd, k=60, align="right", fill=NA )
#      x[,"gdd_ante_90"] <- rollmean( x$gdd, k=90, align="right", fill=NA )
#      x <- slide( data=x, Var="gdd_ante_30", NewVar="pet_ante_30", slideBy=-1, reminder=F )
#      x <- slide( data=x, Var="gdd_ante_60", NewVar="pet_ante_60", slideBy=-1, reminder=F )
#      x <- slide( data=x, Var="gdd_ante_90", NewVar="pet_ante_90", slideBy=-1, reminder=F )



```

```{r junk}

# w_list <- gages_no_barr@data[,c("weather_filename","weather_region","weather_set")]
# w_list <- w_list[!duplicated(gages_no_barr$weather_filename),]
# 
# head(w_list)
# nrow(w_list)
# nrow(gages_no_barr)


```


```{r}

#           ### loop through periods
#           ##
#           #
# 
#           for (j in periods ){ 
#                j<-"month"
#                j<-"wateryear"
#                ### weather aggregation
#                ##
#                #
#                rm(x_total, x_max, x_min, x_mean, x_summary)
#                
#                vars_total <- c( "precip_e", "precip_raw", "pet", "gdd", "swe_day", "frozen_day"  )
#                vars_mean <- c( "tmax", "tmin" )
#                vars_max <- c( "precip_e", "precip_raw", "precip_sum_3", "precip_sum_3", "swe_doy"  )
#                vars_min <- c()
#                
#                # swe_doy_total is used as an indicator of the wateryear (in spring) at which there's snowpack on the ground
#                     #so, it doesn't make sense on a monthly or daily time step, remove it if j isn't wateryear
#                if ( j!="wateryear" )
#                     if ("swe_doy" %in% vars_max)
#                          vars_max <- vars_max[-which(vars_max=="swe_doy")]
# 
#                #set up table
#                x_summary <- x %>% 
#                          select_( paste0(j,"_date") ) %>% 
#                          group_by_( paste0(j,"_date") )  %>% 
#                          summarize( n_days = n() )
#                #add each summary metric
#                if (length(vars_total) > 0 ) {
#                     x_total <- x %>% 
#                          group_by_( paste0(j,"_date") ) %>% 
#                          summarize_each_( "sum", vars_total ) 
#                     x_total <- setNames( x_total, c(  names(x_total[,1]),  paste0(names(x_total[,-1]), "_total") ))
#                     x_summary <- merge( x_summary, x_total, by=paste0(j,"_date") )
#                }
#                if (length(vars_mean) > 0 ) {
#                     x_mean <- x %>% 
#                          group_by_( paste0(j,"_date") ) %>% 
#                          summarize_each_( "mean", vars_mean ) 
#                     x_mean <- setNames( x_mean, c(  names(x_mean[,1]),  paste0(names(x_mean[,-1]), "_mean") ))
#                     x_summary <- merge( x_summary, x_mean, by=paste0(j,"_date") )
#                }
#                if (length(vars_max) > 0 ) {
#                     x_max <- x %>% 
#                          group_by_( paste0(j,"_date") ) %>% 
#                          summarize_each_( "max", vars_max ) 
#                     x_max <- setNames( x_max, c(  names(x_max[,1]),  paste0(names(x_max[,-1]), "_max") ))
#                     x_summary <- merge( x_summary, x_max, by=paste0(j,"_date") )
#                }
#                if (length(vars_min) > 0 ) {
#                     x_min <- x %>% 
#                          group_by_( paste0(j,"_date") ) %>% 
#                          summarize_each_( "min", vars_min ) 
#                     x_min <- setNames( x_min, c(  names(x_min[,1]),  paste0(names(x_min[,-1]), "_min") ))
#                     x_summary <- merge( x_summary, x_min, by=paste0(j,"_date") )
#                }
#                
#                head(x_summary)
#                tail(x_summary)
# 
#                

# 

### weather lag values
##
#
#                x.lag <- weather.lag.function( x.agg )
# 
#                x.final<-as.matrix(x.lag[,cols.weather])
#                w.matrices[[j]][,selected.weather.files$weather.filename[i],]<-x.final
# 
#           }#end loop periods
#                
# 
#           
#      }#end loop weather grids
# 
# #      setwd( orig.dir )
# #      return(w.matrices)
# 
# 


```







```{r}
# my.weather.agg.function<-function(df) {
#      j<-names(df)[1] #way to determine the period, w/o requiring it to be passed as parameter, so only one paramter is needed
#      cutoff<-create.template.periods()[j,"min.records"] #determine number of records for this periods to be considered "complete"
#      return( c(
#           precip.e.total=sum(df$precip.e, na.rm=T),
#           precip.e.max=max(df$precip.e, na.rm=T),
#           #           precip.e.max.date=which.max.date(df,"precip.e"),
#           precip.e.max.date=df[which(df$precip.e==max(df$precip.e,na.rm=T))[1],"date"],
#           max.ties=length(which(df$precip.e==max(df$precip.e,na.rm=T))),
#           precip.raw.total=sum(df$precip.raw, na.rm=T),
#           #           precip.raw.max.date=which.max.date(df,"precip.raw"),
#           precip.raw.max=max(df$precip.raw, na.rm=T),
#           precip.raw.max.date=df[which(df$precip.raw==max(df$precip.raw,na.rm=T))[1],"date"],
#           precip.sum.3.max=max(df$precip.sum.3, na.rm=T),
#           #           precip.sum.3.max.date=which.max.date(df,"precip.sum.3"),
#           precip.sum.3.max.date=df[which(df$precip.sum.3==max(df$precip.sum.3,na.rm=T))[1],"date"],
#           tmin=mean(df$tmin, na.rm=T),
#           tmax=mean(df$tmax, na.rm=T),
#           pet=sum(df$pet, na.rm=T),
#           gdd=sum(df$gdd, na.rm=T),
#           melt.doy=max(df$melt.doy, na.rm=T),
#           complete=sum(!is.na(df$precip.raw))>=cutoff) )
# }

```

```{r}
# my.weather.lag.function <- function (x) {     
#      for ( j in c("precip.e.total","precip.raw.total",  #"precip.e.max","precip.raw.max", 
#                   "pet","gdd","tmax","tmin","melt.doy") ) {
#           for ( i in 1:2 ) {    
#                x <- slide( x, Var=j, NewVar=paste0(j,".lag",i),
#                            slideBy=-i, reminder=F )    }     }
#      return( x )
}
```


```{r}

# #Load/calculate/aggregate weather data for seasonal and annual timesteps
# w.max.matrices<-weather.retrieve( gages.spatial = g.spatial, 
#                                   weather.pre.agg.function = my.weather.pre.agg.function,
#                                   weather.agg.function = my.weather.agg.function,
#                                   weather.lag.function = my.weather.lag.function,
#                                   periods = c("monthly","seasonal", "annual") )

```

```{r}

# head(w.max.matrices[["monthly"]][,1,])
```

```{r main scratch}
#      #loop through weather grid cells and pull and aggregate observation records
#      cat(paste( "Begin processing", nrow(selected.weather.files), "unique weather files used for",nrow(gages.spatial),"gages","\n" ))
#      
#      for (i in 1:nrow(select_weather_files) ) {
#      
#           cat( paste( "  --  Processing file", i, "of", nrow(select_weather_files), "  --  \n" ))
#                     
#           #centroid for selected weather grid
#           centroid <- weather_grid_coords[i, c("x","y")]
# 
#           #           #load mauer weather data, using static mauer column names
#           #           cache.load.data( object="x", 
#           #                            dir=file.path("weather_data",selected.weather.files$region[i]), 
#           #                            file=selected.weather.files$weather.filename[i],
#           #                            is.rdata=F, col.names = cols.mauer )
#           
#           ## load (and pretty up) raw file
#           #
#           
#           x <- read.table( file.path("C:/ALR/Models/cache/data/weather_data", 
#                               weather_set, 
#                               select_weather_files$weather_region[i],
#                               select_weather_files$weather_filename[i]), 
#                               header=F) #mauer data set has headers, livneh doesn't...
#           x <- setNames( x, template_w_cols )
#           x <- cbind( template_w_date, x )
#           
#                         
#           ### weather calculations
#           ##
#           #
#           x <- weather_raw_calc( x, centroid )
#           
# 
#           ### loop through periods to summarize and calulate lags
#           ##
#           #
# 
#           for (j in periods ) { 
#                
#                #summarize (for month and wateryear)
#                if ( j != "day" )  
#                     temp <- weather_summarize( x, j )
#                
#                #calculate antecedent for daily
#                if ( j == "day" ) {
#                     temp <- weather_antecedent( x )
#                     temp <- select( temp, -matches("swe_doy") )
#                } 
#                     
#                
#                #calculate lags 
#                if ( j != "day" )  #month or wateryer
#                     temp <- weather_lag( temp )
#                else { # day (lags are a little different for day)
#                     temp <- weather_lag( temp, 
#                                          lag1_vars=
#                                               c("precip_e","precip_raw","swe","pet","gdd","tmax","tmin"),
#                                          lag2_var=
#                                               c("precip_e","precip_raw","swe","pet","gdd","tmax","tmin") )
#                }
#                
#                #for months, remove records at the beginning that don't have lag values
#                if ( j=="month" ) 
#                     temp <- temp %>% filter( !is.na(n_days_lag2) )
#                
#                
#                #for wateryear, remove records at beginning and end that don't have complete wateryear
#                     #all records have complete calendar year, so our criteria are a bit different
#                if ( j=="wateryear" ) 
#                     temp <- temp %>% filter( n_days >= 365 )
#                
#                assign( paste0("w_summary_",j), temp )
#           } #end loop through periods
#           
#           #assign to massive table, 
#           #    wide by metric, 
#           #    long by site and date/time-step
# 
#      }#end loop through weather grid files
#           

```
